### ISSUE TITLE
Adapt not map to an existing object

### ISSUE THREAD

**Issue by hassan-gasemi** [MSaniee/Use-Mapster-In-DotNet#1]
TEntity ToEntity(TEntity entity) not works as expected.

`public TEntity ToEntity(TEntity entity)
        {
            return this.Adapt(entity);
        }`

this.Adapt(entity) does not map Dto props to Entity props. Maybe it's related to type of the class (abstract) and this keyword.

**Comment by MSaniee** [comment]
Thank you for your attention.
At the moment I solved it with this way :

`public TEntity ToEntity(TEntity entity)
    {
        return (this as TDto).Adapt(entity);     
    }`

Also , I added a "put action" in controller for testing.
As I said Mapster is very simple So you could use this way instead of "ToEntity" Method :

`dto.Adapt(destinationObject);`

**Comment by hassan-gasemi** [comment]
@MSaniee Thanks. I'll test it. Cause of my config for Mapster, BaseDto is ideal way.
